[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
broadcast = "broadcast"

# Solidity compiler settings
solc = "0.8.30"
optimizer = true
optimizer_runs = 1000000
via_ir = true

# Enable FFI for advanced scripting
ffi = true

# File system permissions for reading configuration files
fs_permissions = [
    { access = "read", path = "./config" },
    { access = "read", path = "./deployments" },
    { access = "write", path = "./deployments" },
    { access = "read", path = "." }
]

# Gas reporting
gas_reports = ["*"]

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]

# Test configuration
verbosity = 2

# Fuzzing configuration
[fuzz]
runs = 256
max_test_rejects = 65536

# Invariant testing configuration
[invariant]
runs = 256
depth = 15
fail_on_revert = false

# Development profile for faster compilation during development
[profile.dev]
optimizer = false
via_ir = false

# CI profile for continuous integration
[profile.ci]
optimizer = true
optimizer_runs = 1000000
via_ir = true
verbosity = 4

[profile.ci.fuzz]
runs = 1000

[profile.ci.invariant]
runs = 1000
depth = 20

# Production profile for deployment
[profile.production]
optimizer = true
optimizer_runs = 1000000
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
