# Gas Testing Configuration
# Simple configuration for testing gas consumption

[token]
name = "Gas Test Token"
symbol = "GASTEST"
initial_supply = 0

[governor]
name = "Gas Test Governor"
voting_delay = 1
voting_period = 5760
quorum_numerator = 4
late_quorum_extension = 10



[deployment]
scenario = "basic"
splitter_scenario = "none"
verify = false
save_artifacts = false
custom_salt = ""

[network]
description = "Local Anvil Fork"
chain_id = 31337
gas_price_gwei = 20
gas_limit = 30000000

# Network configurations
[networks.mainnet]
description = "Ethereum Mainnet"
chain_id = 1
gas_price_gwei = 20
gas_limit = 30000000

[networks.local]
description = "Local Anvil"
chain_id = 31337
gas_price_gwei = 20
gas_limit = 30000000

# Distribution scenarios for testing
[distributions.basic]
description = "Basic scenario with 3 recipients"

[[distributions.basic.recipients]]
name = "Recipient 1"
address = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
amount = "1000000000000000000000"  # 1000 tokens
description = "First test recipient"

[[distributions.basic.recipients]]
name = "Recipient 2"
address = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
amount = "2000000000000000000000"  # 2000 tokens
description = "Second test recipient"

[[distributions.basic.recipients]]
name = "Recipient 3"
address = "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
amount = "3000000000000000000000"  # 3000 tokens
description = "Third test recipient"

[distributions.large]
description = "Large scenario with many recipients"

[[distributions.large.recipients]]
name = "Large Recipient 1"
address = "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
amount = "1000000000000000000000"
description = "Large test recipient 1"

[[distributions.large.recipients]]
name = "Large Recipient 2"
address = "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc"
amount = "1000000000000000000000"
description = "Large test recipient 2"

[[distributions.large.recipients]]
name = "Large Recipient 3"
address = "0x976EA74026E726554dB657fA54763abd0C3a0aa9"
amount = "1000000000000000000000"
description = "Large test recipient 3"

[[distributions.large.recipients]]
name = "Large Recipient 4"
address = "0x14dC79964da2C08b23698B3D3cc7Ca32193d9955"
amount = "1000000000000000000000"
description = "Large test recipient 4"

[[distributions.large.recipients]]
name = "Large Recipient 5"
address = "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f"
amount = "1000000000000000000000"
description = "Large test recipient 5"

# Splitter scenarios for testing
[splitters.basic]
description = "Basic 60/40 split"

[[splitters.basic.payees]]
account = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
shares = 6000

[[splitters.basic.payees]]
account = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
shares = 4000

[splitters.three_way]
description = "Three-way split"

[[splitters.three_way.payees]]
account = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
shares = 5000

[[splitters.three_way.payees]]
account = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
shares = 3000

[[splitters.three_way.payees]]
account = "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
shares = 2000

[splitters.none]
description = "No splitter"